version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  commit-message:
    prefix: "chore"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  ignore:
    - dependency-name: "node-polyfill-webpack-plugin"
      # ignore versions > 4.0.0
      versions: [ "^4.1.0" ]

- package-ecosystem: npm
  target-branch: stable1
  directory: "/"
  commit-message:
    prefix: "chore"
    include: "scope"
  versioning-strategy: "increase"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Berlin
  ignore:
    - dependency-name: "node-polyfill-webpack-plugin"
      # ignore versions > 4.0.0
      versions: [ "^4.1.0" ]
